config/routes.rb
Omrails::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :pins, :projects, :charges, :approval

  devise_for :users, :pins, :projects

  root :to => 'pages#home'
  
  get 'learnmore' => 'pages#learnmore'

  get 'successstories' => 'pages#successstories'

  get 'resources' => 'pages#resources'

  

end

app/models/pin.rb
require 'open-uri'
require 'timeout'

class Pin < ActiveRecord::Base

  attr_accessor :image_url, :image_remote_url
  attr_accessible :description, :image, :image_remote_url, :image_url, :approved


  before_validation :download_remote_image, :if => lambda { |pin| pin.image_url.present? }
  
  validates_attachment :image, :presence => true, content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image,gif', 'image/JPG']}, size: { less_than: 5.megabytes }

  validates :description, presence: true
  validates :user_id, presence: true

  belongs_to :user

  has_attached_file :image,
        :storage => :s3,
        :s3_credentials => {
          :bucket => ENV['S3_BUCKET_NAME'],
          :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
          :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
      },
      styles: { 
        thumb: "4800@>",
        small: "160x120>",
        medium: "320x240>",
        large: "640x480>"
       }
  
  private
  
  def image_url_provided?
    !self.image_url.blank?
  end

  def download_remote_image
    return if self.image.present?
    begin
      Timeout::timeout(4) do
        self.image = URI.parse(image_url)
        self.image_remote_url = image_url
      end
    rescue Exception => e
      Rails.logger.error "Failed to download image from \"#{image_url}\": #{e.message}"
    end
  end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.where(approved: true).order("created_at desc").paginate(:page => params[:page], :per_page =>10)
    @admin = user_signed_in?&&current_user.admin?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Image successfully uploaded.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: {class: "form-horizontal"}) do |f| %>
	<! Error commands >
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>


     <%= f.input :image, label:'Upload an Image, or ...' %>

     <%= f.input :image_url, label:'Enter Image URL' %>
     <%= f.input :description, as: :text, input_html: {rows: "3"} %>


  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<%= link_to (image_tag pin.image (:medium)), pin %>


  <p class="description">
  	<%= pin.description %>
  </p>
  <p>
		<strong>
			Posted by <%= pin.user.name %>
		</strong>
	</p>
	<% if current_user == pin.user %>
		<p>
		<%= link_to 'Edit', edit_pin_path(pin) %> &nbsp;
		<%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
		</p>
	<% end %>
	
</div>

app/views/pins/edit.html.erb
<div class="hero-unit"><h1>Replace Image: <%= @pin.description %></h1></div>
<div class="container">
	<p>Current Image:</p>
	<p>
		<%= image_tag @pin.image (:medium) %>
	</p>

	<%= render 'form' %>

	<%= link_to 'Back to This Image\'s Page', @pin %> |
	<%= link_to 'Back to All Images', pins_path %>
</div>

app/views/pins/index.html.erb
<div class="hero-unit"><h1>Popular Projects</h1></div>
	<div class="content">
		<p>
		<%= link_to "Add Your Favorite +", new_pin_path, class: "btn btn-primary btn-large" %>
		</p>
			<div id="pins">
			<%= render @pins %>
			</div>
		<div class="form-actions">
			<div class="pins_pagination">
			<%= will_paginate @pins %>
			</div>
		</div>

	</div>
</div>

app/views/pins/new.html.erb
<div class="hero-unit"><h1>Create a New pin</h1></div>
<div class="container">
	<%= render 'form' %>

	<%= link_to 'Back', pins_path %>
</div>

app/views/pins/show.html.erb
<h1>Viewing <%= @pin.description %></h1>
<div class="container">
	<div class="row">
		<div class="span6 offset3">
			<div class="well">
				
				<%= image_tag @pin.image(:large), class: "img-rounded img-polaroid" %>
			
				<p>
				  <strong>Image Title:</strong> <%= @pin.description %>
				</p>
				<p>
				 <strong>Uploaded By:</strong> <%= @pin.user.name %>
				</p>

				<% if current_user == @pin.user %>
					<%= link_to 'Replace', edit_pin_path(@pin) %>
				<% end %> |

				<%= link_to 'Back to All Images', pins_path %>
			</div>
		</div>
	</div>
</div>