config/routes.rb
Omrails::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :pins, :projects, :charges, :approval

  devise_for :users, :pins, :projects

  root :to => 'pages#home'
  
  get 'learnmore' => 'pages#learnmore'

  get 'successstories' => 'pages#successstories'

  get 'resources' => 'pages#resources'

  

end

app/controllers/approval_controller.rb
class ApprovalController < ApplicationController
    before_filter :authenticate_user!, except: [:index, :show]
    before_filter do
    	redirect_to index_path unless user_signed_in?&&current_user.admin?
    end

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").paginate(:page => params[:page], :per_page =>50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = Pin.find(params[:id])
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = Pin.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to approval_index_path, notice: 'Pin was successfully approved.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end
end

app/helpers/approval_helper.rb
module ApprovalHelper
end

app/views/approval/_approval.html.erb
<div class="box">
	<%= link_to (image_tag pin.image (:medium)), pin %>

  <p class="description">
  	<%= pin.description %>
  </p>
  <p>
		<strong>
			Posted by <%= pin.user.name %>
		</strong>
	</p>
	<% if pin.approved? %>
		<div class="approved">
			<p>Approved</p>
		</div>
	<% else %>
		<div class="approval">
			Awaiting Approval
			</p>
		</div>
	<% end %>

	<%= link_to "Change Approval Status", edit_approval_path(pin) %> &nbsp;
</div>

app/views/approval/_form.html.erb
<%= simple_form_for(@pin, :url => approval_path, html: {class: "form-horizontal"}) do |f| %>
	<! Error commands >
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <p>
    Approved? &nbsp; <%= f.check_box :approved, {}, 'true', 'false' %>
  </p>


  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/approval/edit.html.erb
<div class="hero-unit"><h1>Change Approval Status: <%= @pin.description %></h1></div>
<div class="container">
	<p>Current Image:</p>
	<p>
     <%= image_tag @pin.image %>
  </p>
  <p>   
    <%= @pin.description %>
  </p>

	<%= render 'form' %>

	<%= link_to 'Back to Approvals Page', approval_path %> |
	
</div>

app/views/approval/index.html.erb
	<div class="hero-unit"><h1>Approve Pins</h1>


	</div>
	<div class="content">

	<div id="pins">
		 <%= render partial: 'approval', collection: @pins, as: :pin %>
	</div>
	<div class="form-actions">
		<div class="pins_pagination">
			<%= will_paginate @pins %>
		</div>
	</div>

</div>