config/routes.rb
Omrails::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :pins, :projects, :charges, :approval

  devise_for :users, :pins, :projects

  root :to => 'pages#home'
  
  get 'learnmore' => 'pages#learnmore'

  get 'successstories' => 'pages#successstories'

  get 'resources' => 'pages#resources'

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :blurb, :category, :cost, :description, :progressupdate

	validates :title, :blurb, :description, :user_id, presence: true
	validates :cost, :numericality => true

  belongs_to :user

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order("created_at desc").paginate(:page => params[:page], :per_page =>10)
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = current_user.projects.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = current_user.projects.find(params[:id])
  end

  # POST /project
  # POST /projects.json
  def create
    @project = current_user.projects.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project successfully saved.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  
    <%= f.input :title %>
    <%= f.input :blurb, as: :text, input_html: {rows: "2"}, placeholder: '1 to 2 line description' %>
    <%= f.input :description, as: :text, input_html: {rows: "3"}, placeholder: 'In-depth description of project' %>
    <%= f.input :category, collection: @meta_type, as: :grouped_select, group_method: :types %>
    <%= f.input :cost, label: 'Project Cost: $' %>

    <! -- if project has no title, assume it's new and has no updates, hide update field -->
    <% if @project.title? %> 
      <%= f.input :progressupdate, as: :text, input_html: {rows: "3"}, label:'Update', placeholder: 'Optional - describe any progress that has already been made on this project.', placeholder: 'Describe any progress on your project.' %>
    <% end %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<!-- this file is unused -->
<div class="box">

  <p class="description">
  	<%= project.blurb %>
  </p>
  <p>
		<strong>
			Posted by <%= project.user.name %>
		</strong>
	</p>
	<% if current_user == project.user %>
		<p>
		<%= link_to 'Edit', edit_project_path(project) %> &nbsp;
		<%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %>
		</p>
	<% end %>
</div>

app/views/projects/edit.html.erb
<div class='hero-unit'> <h1>Editing Project: <%= @project.title %></h1></div>
<div class='content'>

	<%= render 'form' %>
	
	<%= link_to 'Back to this Project\'s Page', @project, class: "btn btn-primary btn-large" %> 
	<%= link_to 'View All Projects', projects_path, class: "btn btn-primary btn-large" %>
</div>

app/views/projects/index.html.erb
<div class="hero-unit"><h1>All Projects</h1></div>

<table class="table table-hover table-condensed">
  <tr>
    <th>Title</th>
    <th>Blurb</th>
    <th>Description</th>
    <th>Category</th>
    <th>Cost</th>
    <!-- <th>Progress Update</th> -->
    <th>Owner</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.title %></td>
    <td><%= project.blurb %></td>
    <td><%= project.description %></td>
    <td><%= project.category %></td>
    <td><%= project.cost %></td>
    <!-- <td><%= project.progressupdate %></td> -->
    <td><%= project.user.name %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path, class: "btn btn-primary btn-large" %>

app/views/projects/new.html.erb
<div class="hero-unit"><h1>Create a Project</h1></div>
<div class="container">
	<%= render 'form' %>

	<%= link_to 'Projects Index', projects_path, class: "btn btn-primary btn-large" %>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="hero-unit">
    <h1><%= @project.title %>
    </h1>
  </div>

    <p>
    <b>Blurb:</b>
    <%= @project.blurb %>
    </p>

    <p>
      <b>Description:</b>
      <%= @project.description %>
    </p>

    <p>
      <b>Category:</b>
      <%= @project.category %>
    </p>

    <p>
      <b>Cost:</b>
       $<%= @project.cost %>
    </p>

    <p>
      <b>Progress Update:</b>
      <%= @project.progressupdate %>
    </p>


  <% if current_user == @project.user %>
       <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-primary btn-large' %> &nbsp;
       <%= link_to 'Delete', @project, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-primary btn-large'  %>

  <% end %>
  <%= link_to 'Projects Index', projects_path, class: 'btn btn-primary btn-large' %>
</div>