config/routes.rb
Omrails::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :pins, :projects, :charges, :approval

  devise_for :users, :pins, :projects

  root :to => 'pages#home'
  
  get 'learnmore' => 'pages#learnmore'

  get 'successstories' => 'pages#successstories'

  get 'resources' => 'pages#resources'

  

end

app/views/layouts/_carousel_featured.html.erb
<!--  Carousel - consult the Twitter Bootstrap docs at
      http://twitter.github.com/bootstrap/javascript.html#carousel -->
<div id="this-carousel-id" class="carousel slide"><!-- class of slide for animation -->
  <div class="carousel-inner">
    <div class="item active"><!-- class of active since it's the first item -->
      <span class="center"><img src="https://s3.amazonaws.com/omrails_images/images/featured/SolarOnRoof1200x480.jpg" alt="Solar on a school roof, Black Rock Solar flickr stream, creative commons license" /></span>
      <div class="carousel-caption">
        <p>Sample Photo, not a GPH project: Black Rock Solar's solar roof on Truckee Meadows Community College Vista Building, source: <a href="http://www.flickr.com/photos/freethesun/8552190897/">flickr stream</a>, creative commons license</p>
      </div>
    </div>
    <div class="item">
      <img src="https://s3.amazonaws.com/omrails_images/images/featured/Insulation1200x480.jpg" alt="Insulation project from Velo Steve's creative commons flickr stream, http://www.flickr.com/photos/juniorvelo/" />
      <div class="carousel-caption">
        <p>Sample Photo, not a GPH project: Velo Steve insulation project <a href="http://www.flickr.com/photos/juniorvelo/">Insulation</a>, creative commons license</p>
      </div>
    </div>
    <div class="item">
      <img src="https://s3.amazonaws.com/omrails_images/images/featured/BlowerDoor1200x480.jpg?" alt="Energy audit blower door image, Brandon Strafford, creative commons license, http://www.flickr.com/photos/pingswept/4360064655/lightbox/" />
      <div class="carousel-caption">
        <p>Sample Photo, not a GPH project: Brandon Strafford <a href="http://www.flickr.com/photos/pingswept/4360064655/lightbox/">The blower door in place</a>, creative commons license</p>
      </div>
    </div>
    <div class="item">
      <img src="https://s3.amazonaws.com/omrails_images/images/featured/Wind1200x480.png" alt="Searsburg wind towers, photo from redjar's flickr stream, creative commons license, http://www.flickr.com/photos/redjar/113885464/lightbox/" />
      <div class="carousel-caption">
        <p>Sample Photo, not a GPH project: redjar flickr stream, <a href="http://www.flickr.com/photos/redjar/113885464/lightbox/">Searsburg Wind Power Facility</a>, creative commons license</p>
      </div>
    </div>
  </div><!-- /.carousel-inner -->
  <!--  Next and Previous controls below
        href values must reference the id for this carousel -->
    <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

app/views/layouts/_footer.html.erb
<footer class='section' id='footer' role='contentinfo'>
	
		<div class='row-fluid' style="margin-left: 20px;">

			<div class='span4'>
					<h3>Join us online</h3>
						<ul class='unstyled'>
						<li>
						<i class='icon-twitter'></i>
						<a href='https://twitter.com/GreenPlanetHero/' target='_blank'>Follow @GreenPlanetHero</a>
						</li>
						<li>
						<i class='icon-facebook'></i>
						<a href='https://www.facebook.com/GreenPlanetHeroesCommunity' target='_blank'>Green Planet Heroes Community</a>
						</li>
						<li>
						<div class='fb-like' data-colorscheme='dark' data-href='https://www.facebook.com/GreenPlanetHeroesCommunity' data-layout='button_count' data-send='false' data-show-faces='false' data-width='450' style='margin:2px 0px 5px 40px;'></div>
						</li>
						<li>
						
						</li>
						</ul>
					</div>

					<div class='span4'>
						<h3>Green Planet Heroes</h3>
						<ul class='unstyled'>
							<li>
								<i class='icon-map-marker'></i>
								<a href="#">Contact</a>
							</li>
							<li>
								<i class='icon-bolt'></i>
								<a href="#">About</a>
							</li>
							<li>
								<i class='icon-bookmark-empty'></i>
								<a href="#">FAQ</a>
							</li>
							<li>
								<i class='icon-envelope'></i>
								<a data-toggle='modal' href='#myModal'>Newsletter</a>
							</li>
						</ul>
					</div>

					<div class='span4'>
						<h3>Legal</h3>
						<ul class='unstyled'>
							<li>
								<i class='icon-legal'></i>
								<a href="#">Terms and Conditions</a>
							</li>
							<li>
								<i class='icon-bullhorn'></i>
								<a href="#">Privacy Policy</a>
							</li>
						</ul>						
					</div>

					<div class="span12" style="text-align: center">
						Copyright (c) 2012-2013 Green Planet Heroes
					</div>

			</div>

</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
  	<div class="container">
     
    	<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    	<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    		<span class="icon-bar"></span>
    		<span class="icon-bar"></span>
    		<span class="icon-bar"></span>
    	</a>
     
    	<!-- Be sure to leave the brand out there if you want it shown -->
    		<%= link_to "Green Planet Heroes", root_path, class:"brand" %>
     
    	<!-- Everything you want hidden at 940px or less, place within here -->
    		<div class="nav-collapse collapse">
    			<ul class="nav">
            <li><%= link_to "Learn More", learnmore_path %></li>
            <li><%= link_to "Create Project", new_project_path %></li>
            <li class="dropdown">
              <a href="/projectlist" class="dropdown-toggle" data-toggle="dropdown">Projects <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li class="nav-header">All...</li>
                <li><%= link_to "All Projects Page", projects_path %></li>
                <li class="divider"></li>
                <li class="nav-header">Efficiency...</li>
                <li><a href="#">Air Sealing</a></li>
                <li><a href="#">Cooling</a></li>
                <li><a href="#">Heating</a></li>
                <li><a href="#">Insulation</a></li>
                <li> <a href="#">Lighting</a></li>
                <li class="divider"></li>
                <li class="nav-header">Renewables...</li>
                <li> <a href="#">Solar Electric</a> </li>
                <li> <a href="#">Solar Hot Water</a></li>
                <li> <a href="#">Micro Hydro</a> </li>
                <li> <a href="#">Small Wind</a> </li>
                <li> <a href="#">Community Scale Wind</a> </li>
              </ul>
            </li>
            <li><%= link_to "Success Stories", successstories_path %></li>
            <li><%= link_to "Resources", resources_path %></li>
            <li><%= link_to "Pins", pins_path %></li>

          </ul>
          <div id="GPHSearch" class="input-append search">
            <ul class="nav pull-right">
              <form class="navbar-search">
                  <input type="text" class="input-small " placeholder="Search">
                  <button class="btn btn-primary btn-small"><i class="icon-search icon-white"></i></button>
              </form>
            </ul>
          </div>
    		</div>
<!-- Nav Elements that aren't hidden at 940px or less, place within here -->
          <ul class="nav pull-right">
            <%if user_signed_in?%>
              <li><%= link_to "My Profile", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            <%else%>
              <li><%= link_to "Log In", new_user_session_path %></li>
            <%end%>
             
          </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0" />
		
	  <title>Green Planet Heroes</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	


	</head>
	
		<% flash.each do |key, value| %>
   			<%= content_tag(:div, value, class: "alert alert-#{key}", style: "margin-top: 60px;") %>
		<% end %>
<body>
		<%= render 'layouts/header' %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	 
	</body>
</html>